spring:
  profiles:
    active: dev
mybatis:
  mapper-location:
    - classpath:mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: 666666 #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: Bearer  #JWT负载中拿到开头
