spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 666666
    url: jdbc:mysql://101.132.158.126/sell?characterEncoding=utf-8
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null