spring:
  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-location:
    - classpath:com/jekken/**/*.xml


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: 666666 #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: Bearer  #JWT负载中拿到开头
  refreshTime: 1800 #JWT刷新时间

secure:
  ignored:
    urls: #安全路径白名单
      - /admin/login
      - /admin/register
      -/aaa


